CREATE TABLE IF NOT EXISTS BOOK_MANAGEMENT_TBL (
  BOOK_ID INT NOT NULL
  , BOOK_NAME VARCHAR(255) NOT NULL
  , STOCK INT NOT NULL
  , VERSION INT NOT NULL
  , PRIMARY KEY (BOOK_ID)
);

INSERT INTO BOOK_MANAGEMENT_TBL (BOOK_ID, BOOK_NAME, STOCK, VERSION) VALUES (1, 'Spring boot実践入門', 10, 1);
INSERT INTO BOOK_MANAGEMENT_TBL (BOOK_ID, BOOK_NAME, STOCK, VERSION) VALUES (2, 'JUnit詳解', 200, 3);
INSERT INTO BOOK_MANAGEMENT_TBL (BOOK_ID, BOOK_NAME, STOCK, VERSION) VALUES (3, 'H2DBをはじめる', 1, 1);
